### ISSUE TITLE
Works also on PineBook Pro?

### ISSUE THREAD

**Issue by poVoq** [MadameMalady/Manjaro-Waydroid-Manager#1]
Would be nice if this would also be tested with the Pinebook Pro.

**Comment by MadameMalady** [comment]
Most likely does since the boards are extremely similar, however I do not own a pinebook to test with, you are free to test and submit results if you'd like.

**Comment by MadameMalady** [comment]
Since the description for the repository specifies Manjaro Arm on the Pinephone Pro, I'm going to close this issue for now. If you test it and submit the results in the form of a new issue, I'll add the results to the README.md for others' future reference.
